### ISSUE TITLE
Grade up/down

### ISSUE THREAD

**Issue by Bruno-366** [xpqz/learnapl#12]
the output is:

    6 23 19 22 24 12 11 3 18 20 21 4 1 0 14 9 8 16 17 5 2 7 10 15 13

the text is:

    the smallest element is to be found at index 24. The second-smallest is at index 12. The third smallest at index 6 etc.

should be:

    the smallest element is to be found at index 6. The second-smallest is at index 23. The third smallest at index 19 etc.

**Comment by xpqz** [comment]
Oh, wow, that's bad! Thank you -- should now be corrected.

**Comment by Bruno-366** [comment]
No problem. Thank you for the quick fix :)
