### ISSUE TITLE
Iota Underbar

### ISSUE THREAD

**Issue by awagga** [xpqz/learnapl#17]
⍸ isn't touched on in great enough extent. 

There is a passing comment here - "Note that there is another glyph that looks similar, iota underbar, ⍸, that does something entirely different, so don’t confuse the two!" (And the Finding Thing's section)

Monadic ⍸ is a common way of filtering (especially in trains), besides coming up often in many popular problems for beginners (such as Project Euler), further, dyadic ⍸ is a confusing concept at first which may benefit from a thorough explanation.

Unlike other omitted symbols such as ○,⌹,⍟ & ! - iota underbar's ideas are unique to APL and may be useful for a beginner to be introduced to.

**Comment by xpqz** [comment]
Fixed in 6a46e0547607c4f3882c2ec9e67948be17b8184c
