### ISSUE TITLE
“Introduction” revision

### ISSUE THREAD

**Issue by RojerGS** [xpqz/learnapl#2]
# Revision

Here I include all of the things that, to the best of my knowledge and experience, should be changed/corrected.

 - [x] Inconsistent casing of programming language names (APL, J, K, Q all show up in upper-case, but then we can find java, c, c++, rust, go, etc)
 - [ ] typos and similar issues:
   - [x] "c, c++, Java, Python etc" → "c, c++, Java, Python, etc"
   - [x] "code you write in other languages suddenly become" →  "code you write in other languages suddenly becomes"
   - [x] "Learning how to solve problems the data-parallel way, no loops, no branching is the" → "Learning how to solve problems the data-parallel way, no loops, no branching, is the"
   - [x] "have to be a math-wiz to understand, or benefit from APL" → "have to be a math-wiz to understand, or benefit, from APL"
   - [x] "no other general purpose programming language" → "no other general-purpose programming language"
   - [x] "Tack might seen" → "Tack might seem"
   - [x] "the function takes both a left, and a right argument, like" → "the function takes both a left, and a right, argument, like"
   - [x] "only takes a right-side argument" → "only takes a right argument"
   - [x] "argument, for example factorial, !:" → "argument; for example, factorial !:"
   - [x] "if you hover over a glyph in the menu bar" → "if you hover over a glyph in the language bar"
   - [x] "both its monadic, and dyadic uses, where applicable." → "both its monadic and dyadic uses, where applicable."

# To consider

In here I include things that, from my point of view, would be nice additions/modifications.

 - [x] Adding the link to the original xkcd comic, either as a hyperlink for the image itself, or when you mention the name of xkcd
 - [x] Changing "d-fun" and "dfun" to "dfn" (possibly adding a note on pronunciation, if that was the original concern)
 - [x] Add link to the online mdapl (https://mastering.dyalog.com) when you mention that work on it is afoot
 - [ ] Use double ~ in "an endless source of ~confusion~ joy" to add the actual strikethrough over "confusion"

**Comment by RojerGS** [comment]
Consider going from `⊢` to `⎕←` for explicit output, e.g.

```APL
⊢v ← 9?9
⍝ becomes
⎕← v ← 9?9
```

**Comment by xpqz** [comment]
Still can't get the ~overstrike~ to render properly in the html. Tried the double-tilde but no workie.

**Comment by xpqz** [comment]
Mostly fixed in #2ef1e34

**Comment by RojerGS** [comment]
> On `code you write in other languages suddenly become` -- I think this is the correct form, treating `code` as plural.
> 
> https://www.wordhippo.com/what-is/the-plural-of/code.html

I think "code" here is uncountable (like the link also says it can be) and, therefore, handled as if singular. I always think about the words "rice" or "money". You wouldn't say "rice become cooked after boiling for a bit", nor would you say "my money become wrinkled after I stuff it in my pockets."; in both you'd use "_becomes_".

**Comment by RojerGS** [comment]
> Still can't get the ~overstrike~ to render properly in the jupyterbook html. Tried the double-tilde but no workie.

The jupyter book markdown cheatsheet doesn't talk about strikethrough (https://jupyterbook.org/reference/cheatsheet.html) nor can I find anything about it in two other cheatsheets I reference recurringly (https://www.markdownguide.org/basic-syntax/ and https://daringfireball.net/projects/markdown/syntax#em). Maybe use the `<s>` HTML tag? Using it inline should work without any problem.

**Comment by xpqz** [comment]
Ah yes, inline <s> does the job.

**Comment by xpqz** [comment]
Fixed as part of the larger c04f45f
