### ISSUE TITLE
Font issue (presumably again)

### ISSUE THREAD

**Issue by Tortus-exe** [xpqz/learnapl#24]
Hi,

I'd like to start off with a huge thank you because this book is nigh exactly what I was looking for to learn APL: not overly descriptive so as to waste time describing what is meant by a nested array, but good for someone like me who has experience programming in multiple other languages.

Attached is a screenshot. I am running this on Safari on Mac OS:

<img width="503" alt="スクリーンショット 2022-03-25 午後1 56 44" src="https://user-images.githubusercontent.com/65506144/160199704-bada5f2d-e0ea-4a8c-8f1d-6a45cf6f5f95.png">
 
If you cannot see the image by some miracle of the internet, then just know that the font is not monospace; in fact it is very thin, making spacing go all over the place; it's not impossible but is indeed quite difficult to read and interpret matrices, especially as they get more complex.

I see this isn't the first time you've encountered this issue, and I really commend you for writing this book in the first place! Please do not hesitate to ask questions :)

**Comment by gitonthescene** [comment]
I can’t spot the difference but [MDAPL](https://github.com/Dyalog/MDAPL) seems to have solved this.  Perhaps @rodrigogiraoserrao ca spot the issue.

**Comment by gitonthescene** [comment]
FWIW, I checked that the custom.css between the two are essentially the same:
```$ diff -bu learningapl/custom.css mdapl/custom.css
--- learningapl/custom.css	2022-02-14 00:35:12.000000000 +0900
+++ mdapl/custom.css	2022-04-07 10:21:29.000000000 +0900
@@ -22,3 +22,7 @@
 .table td p, .table th p {
     margin: 0;
 }
+
+.solution.admonition {
+    padding-bottom: 0 !important;
+}
$
```

The .ttf files appear to be different, though.  I don't know if this is the issue or not.
```$ diff mdapl/APL385.ttf learningapl/APL385.ttf 
Binary files mdapl/APL385.ttf and learningapl/APL385.ttf differ
$ file */APL385.ttf          
learningapl/APL385.ttf: HTML document text, Unicode text, UTF-8 text, with very long lines (17464)
mdapl/APL385.ttf:       TrueType Font data, 19 tables, 1st "EBDT", 22 names, Macintosh, Copyright 2016, Adrian Smith, Brook House, Gilling, YORK, UKAPL385 UnicodeRegularAPL385-UnicodeA
$
```

Also worth noting that it looks fine on my iMac, but not on my iPhone.

**Comment by gitonthescene** [comment]
I'm no web guru, but when I connect my Safari's developer tools to my iPhone and check the corresponding span elements posted above, MDAPL lists the font as APL385 Unicode where as Learning APL lists it as Times New Roman.  I'm guessing the issue is almost certainly the ttf file mentioned above.

<img width="929" alt="Screen Shot 2022-04-09 at 5 55 22 PM" src="https://user-images.githubusercontent.com/45531702/162564460-64a2f516-9447-43a3-b358-f457183dd9ac.png">
<img width="992" alt="Screen Shot 2022-04-09 at 5 55 07 PM" src="https://user-images.githubusercontent.com/45531702/162564471-e4134575-210a-479e-9e26-0edd4b8dbe66.png">

**Comment by rodrigogiraoserrao** [comment]
The reason it might be working on your Mac, @gitonthescene, is that you probably have the APL385 font installed on your computer, so LearnAPL sources it locally.
On your iPhone, not so much.

If the .ttf files differ, that's likely the issue, then. I got my .ttf file from http://www.apl385.com/fonts/.

Might be worth ensuring both .ttf files live in the same location (in the `_static` folder, next to the `custom.css` file).

**Comment by gitonthescene** [comment]
@rodrigogiraoserrao - Thanks for replying.  I think you’re right that it finds the fonts locally on my desktop.  Hopefully this fixes the issue for my phone as well.

**Comment by Tortus-exe** [comment]
What's interesting is that this looks like a Jupyter notebook, right? Shouldn't it be some kind of monospaced font if it's a jupyter notebook?

**Comment by gitonthescene** [comment]
I think it has declared using a font which doesn’t load properly.  The fallback font is probably the same for the entire document.

**Comment by rodrigogiraoserrao** [comment]
> What's interesting is that this looks like a Jupyter notebook, right? Shouldn't it be some kind of monospaced font if it's a jupyter notebook? 
> 

The _source_ is a notebook, and if you open the notebook sources, where the custom CSS has no bearing, you will see a monospaced font.

But then it gets built into an HTML page, and then the fallback font is something else.

**Comment by xpqz** [comment]
The font file was indeed broken. I've uploaded a correct (hopefully) version in cc8766a753e9f023cda7adf2dec928799123ba74

I'll leave this open for now until someone tells me it's now working. Thanks for your help, @gitonthescene @rodrigogiraoserrao

**Comment by gitonthescene** [comment]
Looks great now!  Thanks!
